### ISSUE TITLE
Card details on response

### ISSUE THREAD

**Issue by berkayunal** [iyzico/iyzipay-php#4]
Hey,

Is it possible to have the following returned with response. They used to be present in the old API (as account object).

- expire_month
- expire_year
- last_4_digits
- cardholder

Thanks

**Comment by sotuzun** [comment]
@hakanerdogan Could you comment on it?

**Comment by hakanerdogan** [comment]
Hi @berkayunal,
First of all thank you for your contribution.

I think you're mentioning about API not Checkout Form or Common Payment Page solution. Since you're, as a merchant, accepting card information in your payment form, you have all these sensitive information before sending them to us for processing.
We're storing all those sensitive information in an encrypted DB by using HSM device. And you may use our tokenization (one click payment ) solution to make recurring payments. Therefore yo may not need all those data after a successful payment.

**Comment by berkayunal** [comment]
@hakanerdogan thanks for the reply but I was mentioning Checkout Form.

Some of these informations are available in the dashboard (Can be dencrypted?)  ("Kart Sahibinin Adı", "Son 4 Hane" as on https://merchant.iyzipay.com/payment/XXX)  and they were also all available in the deprecating (older) system (as account object in the response). Since the Checkout Form is used there is no way to store these locally before making the request.

Fields like "Son 4 Hane" plays important role as it may be used to validate the owner of the order during a phone call and on some other scenarios.

**Comment by hakanerdogan** [comment]
@berkayunal got your requirement, we'll discuss it with the team and find a comprehensive solution, and
let you know.
Best
