### ISSUE TITLE
[Request] Checkout Form callback as target="top"

### ISSUE THREAD

**Issue by berkayunal** [iyzico/iyzipay-php#5]
Hi,

In the previous system the checkout form was posting to callback with target "top". This was enabling the checkout form to be used in iframe with no problem.  In the new system Checkout form is posting to current window (if used in iframe the callback is called in iframe)

Can you implement the callback posting with target "top" as it was in the prior system.

Thanks

**Comment by hakanerdogan** [comment]
@berkayunal we got your 3 requirements, we'll discuss them and add them to our product backlog.

So, I'm closing all these issues, since they are related with API, CO Form or core features, not related with PHP or other clients. Thank you for your feedback and please feel free to write us your needs to entegrasyon@iyzico.com 
Best
