### ISSUE TITLE
cardType problem

### ISSUE THREAD

**Issue by rhnkyr** [iyzico/iyzipay-php#81]
Hi there,

today we have noticed that when we use a common credit card php throws undefined property : cardType. Before we could use this code without issue. 

The code

```
$installmentRequest = new Iyzipay\Request\RetrieveInstallmentInfoRequest();
        $installmentRequest->setLocale(Iyzipay\Model\Locale::TR);
        $installmentRequest->setConversationId($user->id . '-' . random_int(1, 10000));
        $installmentRequest->setBinNumber(substr($info->cc_no, 0, 6)); //bin
        $installmentRequest->setPrice($info->credit); // fiyat

        $installmentInfo    = Iyzipay\Model\InstallmentInfo::retrieve($installmentRequest, $this->Options());
        $installmentDetails = $installmentInfo->getRawResult();
        $installmentResult  = json_decode($installmentDetails);

        if ($installmentResult->installmentDetails[0]->cardType === 'DEBIT_CARD')
```

So what would be the issue? 

Thanks in advance.

**Comment by byasarcse** [comment]
Hello,

CardType parameter exist in the response 

[binNumber:Iyzipay\Model\InstallmentDetail:private] => 554960
[price:Iyzipay\Model\InstallmentDetail:private] => 100
[cardType:Iyzipay\Model\InstallmentDetail:private] => CREDIT_CARD
[cardAssociation:Iyzipay\Model\InstallmentDetail:private] => MASTER_CARD
[cardFamilyName:Iyzipay\Model\InstallmentDetail:private] => Bonus
[force3ds:Iyzipay\Model\InstallmentDetail:private] => 0
[bankCode:Iyzipay\Model\InstallmentDetail:private] => 62
[bankName:Iyzipay\Model\InstallmentDetail:private] => Garanti Bankası
[forceCvc:Iyzipay\Model\InstallmentDetail:private] => 0
[commercial:Iyzipay\Model\InstallmentDetail:private] => 0

Closing the issue due to timed out.
